# distributed training
nodes: 1
gpus: 1 # I recommend always assigning 1 GPU to 1 node
nr: 0 # machine nr. in node (0 -- nodes - 1)
dataparallel: 0 # Use DataParallel instead of DistributedDataParallel
workers: 8
dataset_dir: "./datasets"

# Data option
modality: mri
ad: True
mci: True
stable: True
dir_label: '../getlabels'
num_label: 2
free: '_coreg' # '_coreg' if Data_free
resize: True
dir_data: '../Data_free'
transform: True
save_samples: False
flip: True
local_shuffle_pixel: True
non_inear_ransformation: True
in_painting: True
out_painting: True

# train options
seed: 42 # sacred handles automatic seeding when passed in the config
batch_size: 32
image_size: (128,128,128)
start_epoch: 0
epochs: 100
finetune: False

#dataset: "CIFAR10" # STL10
#pretrain: True

# model options
model: vit_huge_patch14
projection_dim: 64 # "[...] to project the representation to a 128-dimensional latent space"

# loss options
optimizer: "LARS" # or LARS (experimental)
weight_decay: 1.0e-6 # "optimized using LARS [...] and weight decay of 10âˆ’6"
temperature: 0.5 # see appendix B.7.: Optimal temperature under different batch sizes

# reload options
model_path: "huge_p14" # set to the directory containing `checkpoint_##.tar`
epoch_num: 200 # set to checkpoint number
reload: False

# logistic regression options
logistic_batch_size: 256
logistic_epochs: 500

# Image transformation

nonlinear_rate: 0.9
paint_rate: 0.9
outpaint_rate: 0.8
inpaint_rate: 0.2 #1.0- outpaint_rate
local_rate: 0.5
flip_rate: 0.4